### ISSUE TITLE
覆盖后一直更新转圈，无法进入notion

### ISSUE THREAD

**Issue by DoiiarX** [tuanzi0701/notion_cn#7]
![image](https://github.com/tuanzi0701/notion_cn/assets/25550075/a5d435cd-fea7-46e7-860c-dc04d2fe84f9)

**Comment by suiucat** [comment]
参考下这个解决方式 https://github.com/tuanzi0701/notion_cn/issues/5

**Comment by DoiiarX** [comment]
这下有两个转圈的了。

![image](https://github.com/tuanzi0701/notion_cn/assets/25550075/2620e53c-f282-47f4-abcf-b7b5a930d871)

**Comment by DoiiarX** [comment]
替换为日语后重启解决了。
